# Serve the formulae in this directory from a local tap, as Homebrew only installs formulae from taps.
# (Not using `brew tap-new` as it also turns on the developer mode.)
local_tap = HOMEBREW_LIBRARY/"Taps/ruohola/homebrew-dotfiles/Formula"
local_tap.mkpath
Dir[File.expand_path("~/dotfiles/brew/*.rb")].each { |formula| FileUtils.ln_sf(formula, local_tap) }

brew "actions-languageserver"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "cabal-install"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "fd"
brew "fontforge"
brew "fzf"
brew "gh"
brew "ghc"
brew "git"
brew "git-absorb"
brew "git-delta"
brew "git-lfs"
brew "glow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "grep"
brew "haskell-language-server"
brew "jless"
brew "jq"
brew "languagetool"
brew "moreutils"
brew "ncurses"
brew "num-utils"
brew "nvm"
brew "pam-reattach"
brew "pgcli"
brew "pinentry-mac"
brew "pngpaste"
brew "poppler"
brew "pyenv"
brew "pyenv-virtualenv"
brew "readline"
brew "ripgrep"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "tcl-tk@8"
brew "terminal-notifier"
# 3.8 for `#{hook_new_title}`, go back to `brew "tmux"` once it's in Homebrew.
brew "ruohola/dotfiles/tmux@3.8", trusted: true
brew "tombi"
brew "tpack"
brew "tree"
brew "vim"
brew "wget"
brew "yazi"
brew "yq"
brew "zk"
brew "zoxide"
# Don't use `terraform-ls` as it omits the provider schema bundles and
# thus doesn't understand any actual TF code.
brew "hashicorp/tap/terraform-ls", trusted: true
brew "morantron/tmux-fingers/tmux-fingers", trusted: true
brew "raine/tmux-snaglord/tmux-snaglord", trusted: true
brew "raine/aven/aven", trusted: true
brew "smudge/smudge/nightlight", trusted: true
# Optional dependencies for yazi.
brew "ffmpeg-full", link: :overwrite
brew "imagemagick-full", link: :overwrite
brew "resvg"
brew "sevenzip"
brew "exiftool"
