#!/bin/sh
exec /usr/local/bin/ccls -init='{"clang":{"extraArgs":["-isystem", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include", "-isystem", "/Library/Developer/CommandLineTools/usr/include/c++/v1", "-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"]}}' "$@"
