#!/usr/bin/env bash

# Git commit browser
# (Reference from: https://gist.github.com/junegunn/f4fca918e937e6bf5bad)
# enter   show commit
# ctrl-d  diff to current
# ctrl-n  copy commit message
# ctrl-h  copy commit hash
# ctrl-s  copy commit shorthash
# ctrl-f  fill commit shorthash to cursor input (tmux only)

pbcopyn () {
    # Like normal `pbcopy` but strips away all trailing newlines.
    printf '%s' "$(< /dev/stdin)" | pbcopy
}

while out="$(
    git log --graph --color=always "$@" \
        | sed $'s/..\x08\x08 /\xc2\xa0/' \
        | fzf --ansi --multi --no-sort --reverse --delimiter=$'\xc2\xa0' --nth=2 \
              --query="$selected" --print-query --expect=ctrl-d,ctrl-n,ctrl-h,ctrl-s,ctrl-f)"
    # nbsp as invisible delimiter ^ to only match starting from the commit subject.
do
    selected="$(head -1 <<< "$out")"
    key="$(head -2 <<< "$out" | tail -1)"
    shas="$(sed '1,2d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')"
    [ -z "$shas" ] && continue
    if [ "$key" = ctrl-d ]; then
        clear
        git diff --color=always "$shas" | delta --paging=always
    elif [ "$key" = ctrl-n ]; then
        # shellcheck disable=SC2086  # Not quoted to allow copying many.
        git show --no-patch --format=%s $shas | pbcopyn
        break
    elif [ "$key" = ctrl-h ]; then
        # shellcheck disable=SC2086  # Not quoted to allow copying many on a single line.
        git rev-parse $shas | xargs | pbcopyn
        break
    elif [ "$key" = ctrl-s ]; then
        # shellcheck disable=SC2086  # Not quoted to allow copying many on a single line.
        echo -n $shas | pbcopyn
        break
    elif [ "$key" = ctrl-f ]; then
        # shellcheck disable=SC2086  # Not quoted to allow filling many on a single line.
        tmux send-keys -l "$(echo -n $shas)"
        break
    else
        clear
        for sha in $shas; do
            git show --format=fuller --first-parent --color=always "$sha" | delta --paging=always --pager='less +g'
        done
    fi
done

clear
