#!/bin/sh

# Quick Look file(s) on macOS, like on Finder with space bar.

# (The tool is quite verbose.)
qlmanage -p "$@" > /dev/null 2>&1 &
osascript -e 'tell app "System Events" to set frontmost of process "qlmanage" to true'
