set -g default-terminal "xterm-256color"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Show info messages for a longer time.
set-option -g display-time 2000

# Don't use vi mode in command mode editin.
set-option -g status-keys emacs

# Enable mouse support and stay in copy mode after mouse selection.
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

# Get rid of delay from Esc (needed for Vim meta key  mappings)
set -s escape-time 0

# Start window numbers from 1 and remove number gaps when closing windows.
set -g base-index 1
set -g renumber-windows on

# Make Vim `set autoread` work.
set -g focus-events on

# Show full session name in status bar.
set -g status-left-length 99

# Use UTC date in status bar.
set -g status-right '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" #(gdate --utc "+%%a %%Y-%%m-%%d %%H:%%M")'

# Stay in a tmux session when killing another one.
set -g detach-on-destroy off

# Make these easier to use (matches similar remapping logic in Vim)
bind , command-prompt
bind . last-pane
bind \; command-prompt -I "#W" { rename-window "%%" }
bind : command-prompt -T target { move-window -t "%%" }

# Simplify resizing and moving between panes.
# (The default meta-mappings don't work with iTerm2 word-moving override.)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r Left resize-pane -L 1
bind -r Down resize-pane -D 1
bind -r Up resize-pane -U 1
bind -r Right resize-pane -R 1
bind -r C-Left resize-pane -L 5
bind -r C-Down resize-pane -D 5
bind -r C-Up resize-pane -U 5
bind -r C-Right resize-pane -R 5
unbind M-Left
unbind M-Down
unbind M-Up
unbind M-Right

# Open new panes and windows in the current directory, allow repeating the first two.
bind -r % split-window -h -c "#{pane_current_path}"
bind -r \" split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Remap away from `l`.
bind -r b last-window
