set -g default-terminal "xterm-256color"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set-option -g display-time 2000

set-option -g status-keys emacs

set -g mouse on
set -s escape-time 0

set -g base-index 1
set -g renumber-windows on

# Make these easier to use (matches similar remapping logic in Vim)
bind , command-prompt
bind . last-pane
bind \; command-prompt -I "#W" { rename-window "%%" }
bind : command-prompt -T target { move-window -t "%%" }
