set -g default-terminal "xterm-256color"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Show info messages for a longer time.
set-option -g display-time 2000

# Don't use vi mode in command mode editin.
set-option -g status-keys emacs

# Enable mouse support and stay in copy mode after mouse selection.
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

# Get rid of delay from Esc (needed for Vim meta key  mappings)
set -s escape-time 0

# Start window numbers from 1 and remove number gaps when closing windows.
set -g base-index 1
set -g renumber-windows on

# Make Vim `set autoread` work.
set -g focus-events on

# Allow remapping <C-I> and <TAB> separately in Vim.
set -s extended-keys on
set -as terminal-features ',xterm-256color:extkeys'

# Make these easier to use (matches similar remapping logic in Vim)
bind , command-prompt
bind . last-pane
bind \; command-prompt -I "#W" { rename-window "%%" }
bind : command-prompt -T target { move-window -t "%%" }

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Simplify resizing from C-Space C-Arrows.
# (Can still resize by larger increments with C-Space M-Arrows.)
bind -r Left resize-pane -L 1
bind -r Down resize-pane -D 1
bind -r Up resize-pane -U 1
bind -r Right resize-pane -R 1

# Remap splitting to resemble Vim.
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# New windows open in the current directory.
bind c new-window -c "#{pane_current_path}"

# Remap away from `s`.
bind \" choose-tree

# Remap away from `l`.
bind b last-window

bind % source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"
